# Generated by Django 4.2 on 2024-08-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Last name'),
        ),
    ]
