# Generated by Django 4.2 on 2024-09-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usercustommodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='date_birch',
            field=models.DateField(verbose_name='User birch'),
        ),
    ]
